services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=Pagamentos

volumes:
  postgres-data:
